# Generated by Django 4.1 on 2022-08-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngresarFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('cumple', models.CharField(blank=True, max_length=10, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
